preload = ~/Pictures/Wallpapers/green-trunk.jpg
preload = ~/Pictures/Wallpapers/misty-forest.jpg
preload = ~/Pictures/Wallpapers/foresty-island.jpg
preload = ~/Pictures/Wallpapers/jungly-forest.jpg

splash=false

# wallpaper = , ~/Pictures/Wallpapers/misty-forest.jpg
# wallpaper = , ~/Pictures/Wallpapers/green-trunk.jpg

wallpaper {
    #monitor = HDMI-A-3
    monitor = 
    path = ~/Pictures/Wallpapers/misty-forest.jpg
    fit_mode = cover
}
